# Generated by Django 4.1.13 on 2024-04-13 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=25)),
                ('LastName', models.CharField(max_length=25)),
                ('Email', models.EmailField(max_length=254)),
                ('City', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=25)),
                ('Mobile', models.BigIntegerField()),
            ],
        ),
    ]
